# Copyright (2024) Tsinghua University, Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

model:
  # paths
  qwen_path: "../Qwen3.5-9B/models--Qwen--Qwen3.5-9B/snapshots/c202236235762e1c871ad0ccb60c8ee5ba337b9a/"
  whisper_path: "../whisper-large-v2/models--openai--whisper-large-v2/snapshots/ae4642769ce2ad8fc292556ccea8e901f1530655/"
  wav2vec2_path: "../wav2vec2-xls-r-300m/"
  ckpt: "" # "outputs/asv19_no_reasoning/checkpoint_best.pth" # if not "", load model from ckpt for training or evaluation

  freeze_whisper: True
  freeze_wav2vec2: True

  speech_qwen_proj_model: ""
  freeze_speech_qwen_proj: False

  # LoRA
  lora: True
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.1

  multi_prompt: True
  prompt_template: "USER: {}\nASSISTANT:"
  prompt_path: "prompts/train_prompt.json"
  test_prompt_path: "prompts/test_prompt.json"
  max_txt_len: 300
  end_sym: ""

datasets:
  train_ann_path: "/netscratch/fkallel/dfd_llm/asvspoof19_train.json"
  valid_ann_path: "/netscratch/fkallel/dfd_llm/asvspoof19_dev.json"
  test_ann_path: "/netscratch/fkallel/dfd_llm/asvspoof19_eval.json"

  whisper_path: "openai/whisper-large-v2"
  wav2vec2_path: "facebook/wav2vec2-xls-r-300m"

run:
  # log & settings
  seed: 42
  output_dir: "outputs"
  evaluate: False # if True, only evaluate model on test data

  log_freq: 5
  epoch_based: False
  iters_per_epoch: 3000
  accum_grad_iters: 1
  batch_size_train: 1
  batch_size_eval: 1
  num_workers: 1

  device: "cuda"
  use_distributed: True
  amp: True
  world_size: 1
  dist_url: "env://"

  # optimizer & scheduler
  optims:
    max_epoch: 30
    warmup_steps: 3000
    warmup_start_lr: 1e-6
    init_lr: 3e-5
    min_lr: 1e-5
    weight_decay: 0.05
    beta2: 0.999